import type { ResourceConfig } from "@/components/admin/ResourceManager";

export const COUNTRY_OPTIONS = [
  "India",
  "Malaysia",
  "Singapore",
  "UAE",
  "Indonesia",
  "Vietnam",
  "Sri Lanka",
  "Other",
];

export const PERSON_TYPES = [
  "Director – Training",
  "Senior Trainer",
  "Trainer",
  "Expert",
  "Speaker",
  "Consultant",
  "Other",
];

export const PROGRAM_CATEGORIES = [
  "Student Development",
  "Teacher Development",
  "Corporate & Professional Development",
  "Personal Effectiveness",
  "Communication & Leadership",
  "Cognitive & Memory Training",
  "Teaching & Education Skills",
  "Other Professional Training",
];

export const TOPIC_GROUPS = [
  "Focus & Concentration",
  "Memory & Brain",
  "Study & Academic Skills",
  "Personal Development",
  "Future & Career",
  "Teaching & Communication",
  "Engagement & Motivation",
  "Classroom Management",
  "Assessment & Curriculum",
  "Professional Skills",
  "Cognitive Skills",
  "Communication",
  "Leadership & People",
  "Thinking",
  "Professional Development",
  "Other",
];

export const EXPERTISE_CATEGORIES = [
  "Super Memory",
  "Brain Gym",
  "Concentration",
  "Scientific Study Methods",
  "Attitude Development",
  "Communication Skills",
  "Body Language",
  "Leadership",
  "NLP",
  "Lateral Thinking",
  "Placement Support",
  "Effective Teaching",
  "TESOL / TKT",
  "Personality Development",
  "Graphology",
  "Teamwork",
  "Work Ethics",
  "Stress Management",
];

export const INSTITUTION_TYPES = ["School", "College", "University", "Corporate", "Other"];

export const GALLERY_CATEGORIES = [
  "Student Training",
  "Teacher Training",
  "Student Workshops",
  "Teacher Workshops",
  "Corporate Training",
  "International Training",
  "Events",
  "Trainers",
  "Other",
];

export const trainersResource: ResourceConfig = {
  table: "trainers",
  title: "People / Trainers & Experts",
  singular: "Person",
  description:
    "Every published person appears on the public Trainers & Experts page. Add trainers, senior trainers, experts or speakers here.",
  listPrimary: "name",
  listSecondary: ["person_type", "professional_title", "qualification"],
  imageColumn: "photo_url",
  searchColumns: ["name", "person_type", "professional_title", "qualification", "position", "short_bio"],
  filters: [{ column: "person_type", label: "Person type", options: PERSON_TYPES }],
  orderColumn: "display_order",
  publishColumn: "published",
  featuredColumn: "featured",
  softDelete: true,
  previewPath: "/trainers",
  emptyTitle: "No trainers added yet.",
  emptyBody: "Add your first person to show them on the public Trainers & Experts page.",
  defaultValues: { person_type: "Trainer" },
  fields: [
    { name: "name", label: "Name", type: "text", required: true, placeholder: "Dr. K. Akbar Hussain" },
    { name: "person_type", label: "Person type", type: "select", options: PERSON_TYPES, required: true },
    { name: "professional_title", label: "Professional title", type: "text", placeholder: "Corporate & Education Trainer" },
    { name: "qualification", label: "Qualification", type: "text", placeholder: "MSc, MS, D.Litt." },
    { name: "position", label: "Position", type: "text", placeholder: "Director, Limra Academy" },
    { name: "short_bio", label: "Short biography", type: "textarea", help: "Shown on cards and listings." },
    { name: "full_bio", label: "Full biography", type: "richtext" },
    { name: "photo_url", label: "Profile photo", type: "image", mediaCategory: "Trainers" },
    { name: "additional_photos", label: "Additional photos", type: "gallery", mediaCategory: "Trainers" },
    {
      name: "training_areas",
      label: "Expertise / training areas",
      type: "tags",
      placeholder: "Super Memory, Brain Gym",
      help: "Type any expertise category. Suggested: " + EXPERTISE_CATEGORIES.slice(0, 8).join(", ") + "…",
    },
    { name: "regions", label: "Countries / regions", type: "tags", placeholder: "India, Malaysia" },
    { name: "email", label: "Email (optional)", type: "text" },
    { name: "phone", label: "Phone (optional)", type: "text" },
    { name: "linkedin_url", label: "LinkedIn URL (optional)", type: "text" },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "featured", label: "Featured on homepage", type: "switch" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const programsResource: ResourceConfig = {
  table: "programs",
  title: "Programs",
  singular: "Program",
  description: "Training programs shown on the public Programs page.",
  listPrimary: "name",
  listSecondary: ["category", "target_audience", "duration"],
  imageColumn: "image_url",
  searchColumns: ["name", "category", "short_description", "target_audience", "workshop_format"],
  filters: [{ column: "category", label: "Categories", options: PROGRAM_CATEGORIES }],
  orderColumn: "display_order",
  publishColumn: "published",
  featuredColumn: "featured",
  softDelete: true,
  duplicate: true,
  previewPath: "/programs",
  emptyTitle: "No programs added yet.",
  emptyBody: "Add your first program, for example Train the Brain.",
  fields: [
    { name: "name", label: "Program name", type: "text", required: true },
    { name: "slug", label: "URL slug", type: "text", placeholder: "train-the-brain", help: "Used in the page address." },
    { name: "category", label: "Category", type: "select", options: PROGRAM_CATEGORIES },
    { name: "short_description", label: "Short description", type: "textarea" },
    { name: "full_description", label: "Full description", type: "richtext" },
    { name: "target_audience", label: "Target audience", type: "text", placeholder: "School students of VII - XII" },
    { name: "duration", label: "Duration", type: "text", placeholder: "1 day / 5 hours" },
    { name: "workshop_format", label: "Workshop format", type: "text", placeholder: "Interactive on-campus workshop" },
    { name: "image_url", label: "Program image", type: "image", mediaCategory: "Homepage" },
    { name: "gallery_images", label: "Gallery images", type: "gallery", mediaCategory: "Student Workshops" },
    {
      name: "trainers",
      label: "Trainers",
      type: "multirelation",
      relation: { table: "trainers", labelColumn: "name" },
      join: { table: "program_trainers", selfColumn: "program_id", otherColumn: "trainer_id" },
    },
    {
      name: "topics",
      label: "Training topics",
      type: "multirelation",
      relation: { table: "training_topics", labelColumn: "name" },
      join: { table: "program_topics", selfColumn: "program_id", otherColumn: "topic_id" },
    },
    {
      name: "countries",
      label: "Country availability",
      type: "multirelation",
      relation: { table: "countries", labelColumn: "name" },
      join: { table: "program_countries", selfColumn: "program_id", otherColumn: "country_id" },
    },
    { name: "cta_text", label: "Button text", type: "text", placeholder: "Enquire about this program" },
    { name: "cta_link", label: "Button link", type: "text", placeholder: "/contact" },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "featured", label: "Featured on homepage", type: "switch" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const topicsResource: ResourceConfig = {
  table: "training_topics",
  title: "Training Topics",
  singular: "Topic",
  description: "Reusable topics you can attach to any program.",
  listPrimary: "name",
  listSecondary: ["category", "topic_group", "description"],
  searchColumns: ["name", "description", "category", "topic_group"],
  filters: [
    { column: "category", label: "Categories", options: PROGRAM_CATEGORIES },
    { column: "topic_group", label: "Groups", options: TOPIC_GROUPS },
  ],
  orderColumn: "display_order",
  publishColumn: "published",
  softDelete: true,
  emptyTitle: "No training topics yet.",
  emptyBody: "Add topics such as Super Memory or Communication Skills.",
  fields: [
    { name: "name", label: "Topic name", type: "text", required: true },
    { name: "description", label: "Description", type: "textarea" },
    { name: "icon", label: "Icon name", type: "text", placeholder: "brain", help: "Optional Lucide icon name." },
    { name: "category", label: "Category", type: "select", options: PROGRAM_CATEGORIES },
    {
      name: "topic_group",
      label: "Group heading",
      type: "select",
      options: TOPIC_GROUPS,
      help: "Topics are shown grouped under this heading on program pages.",
    },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const institutionsResource: ResourceConfig = {
  table: "institutions",
  title: "Institutions",
  singular: "Institution",
  description: "Schools, colleges, universities and corporate organizations you have trained.",
  listPrimary: "name",
  listSecondary: ["institution_type", "city", "country_name"],
  imageColumn: "logo_url",
  searchColumns: ["name", "city", "country_name", "state_region", "training_conducted"],
  filters: [
    { column: "institution_type", label: "Types", options: INSTITUTION_TYPES },
    { column: "country_name", label: "Countries", options: COUNTRY_OPTIONS },
  ],
  orderColumn: "display_order",
  publishColumn: "published",
  featuredColumn: "featured",
  softDelete: true,
  previewPath: "/institutions",
  emptyTitle: "No institutions added yet.",
  emptyBody: "Add your first school, college, university or corporate client.",
  defaultValues: { institution_type: "School" },
  fields: [
    { name: "name", label: "Institution name", type: "text", required: true },
    { name: "institution_type", label: "Institution type", type: "select", options: INSTITUTION_TYPES, required: true },
    { name: "country_name", label: "Country", type: "select", options: COUNTRY_OPTIONS },
    { name: "country_id", label: "Linked country record", type: "relation", relation: { table: "countries", labelColumn: "name" } },
    { name: "state_region", label: "State / region", type: "text" },
    { name: "city", label: "City", type: "text" },
    { name: "address", label: "Address", type: "textarea" },
    { name: "website_url", label: "Website URL", type: "text" },
    { name: "logo_url", label: "Logo", type: "image", mediaCategory: "Institutions" },
    { name: "cover_image_url", label: "Cover image", type: "image", mediaCategory: "Institutions" },
    { name: "gallery_images", label: "Gallery images", type: "gallery", mediaCategory: "Institutions" },
    { name: "training_conducted", label: "Training conducted", type: "text", placeholder: "Train the Brain" },
    { name: "training_category", label: "Training category", type: "text" },
    { name: "year", label: "Year (optional)", type: "number" },
    { name: "description", label: "Description", type: "richtext" },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "featured", label: "Featured on homepage", type: "switch" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const countriesResource: ResourceConfig = {
  table: "countries",
  title: "Countries",
  singular: "Country",
  description: "Countries shown in the Global Reach section. The public map updates automatically.",
  listPrimary: "name",
  listSecondary: ["code", "description"],
  imageColumn: "featured_image_url",
  searchColumns: ["name", "code", "description"],
  orderColumn: "display_order",
  publishColumn: "published",
  softDelete: true,
  previewPath: "/global-reach",
  emptyTitle: "No countries added yet.",
  emptyBody: "Add the countries where Limra has delivered training.",
  fields: [
    { name: "name", label: "Country name", type: "text", required: true },
    { name: "code", label: "Country code", type: "text", placeholder: "IN" },
    { name: "flag_emoji", label: "Flag", type: "text", placeholder: "🇮🇳" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "training_count", label: "Training count", type: "number" },
    { name: "featured_image_url", label: "Featured image", type: "image", mediaCategory: "International Training" },
    { name: "latitude", label: "Map marker latitude", type: "number" },
    { name: "longitude", label: "Map marker longitude", type: "number" },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const albumsResource: ResourceConfig = {
  table: "gallery_albums",
  title: "Gallery Albums",
  singular: "Album",
  description: "Group gallery images into albums.",
  listPrimary: "name",
  listSecondary: ["category", "description"],
  imageColumn: "cover_image_url",
  searchColumns: ["name", "category", "description"],
  filters: [{ column: "category", label: "Categories", options: GALLERY_CATEGORIES }],
  orderColumn: "display_order",
  publishColumn: "published",
  softDelete: true,
  previewPath: "/gallery",
  emptyTitle: "No albums yet.",
  emptyBody: "Create your first album, for example Student Workshops.",
  fields: [
    { name: "name", label: "Album name", type: "text", required: true },
    { name: "slug", label: "URL slug", type: "text" },
    { name: "category", label: "Category", type: "select", options: GALLERY_CATEGORIES },
    { name: "description", label: "Description", type: "textarea" },
    { name: "cover_image_url", label: "Cover image", type: "image", mediaCategory: "Student Workshops" },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const galleryImagesResource: ResourceConfig = {
  table: "gallery_images",
  title: "Gallery Images",
  singular: "Image",
  description: "Published images appear on the public Gallery page.",
  listPrimary: "title",
  listSecondary: ["category", "city", "country"],
  imageColumn: "image_url",
  searchColumns: ["title", "caption", "alt_text", "city", "country", "category"],
  filters: [{ column: "category", label: "Categories", options: GALLERY_CATEGORIES }],
  orderColumn: "display_order",
  publishColumn: "published",
  featuredColumn: "featured",
  softDelete: true,
  previewPath: "/gallery",
  emptyTitle: "No gallery images yet.",
  emptyBody: "Upload your first workshop image.",
  fields: [
    { name: "image_url", label: "Image", type: "image", required: true, mediaCategory: "Student Workshops" },
    { name: "title", label: "Title", type: "text" },
    { name: "caption", label: "Caption", type: "text" },
    { name: "alt_text", label: "Alt text", type: "text", help: "Describes the image for accessibility and SEO." },
    { name: "album_id", label: "Album", type: "relation", relation: { table: "gallery_albums", labelColumn: "name" } },
    { name: "category", label: "Category", type: "select", options: GALLERY_CATEGORIES },
    { name: "taken_on", label: "Date", type: "date" },
    { name: "country", label: "Country", type: "select", options: COUNTRY_OPTIONS },
    { name: "city", label: "City", type: "text" },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "featured", label: "Featured", type: "switch" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const testimonialsResource: ResourceConfig = {
  table: "testimonials",
  title: "Testimonials",
  singular: "Testimonial",
  description: "Testimonials stay hidden until you approve and publish them.",
  listPrimary: "name",
  listSecondary: ["designation", "organization", "country"],
  imageColumn: "photo_url",
  searchColumns: ["name", "organization", "designation", "quote", "country"],
  filters: [{ column: "country", label: "Countries", options: COUNTRY_OPTIONS }],
  orderColumn: "display_order",
  publishColumn: "published",
  featuredColumn: "featured",
  softDelete: true,
  emptyTitle: "No testimonials yet.",
  emptyBody: "Add a testimonial you have received. It stays unpublished until you approve it.",
  defaultValues: { published: false },
  fields: [
    { name: "name", label: "Name", type: "text", required: true },
    { name: "designation", label: "Designation", type: "text" },
    { name: "organization", label: "Organization", type: "text" },
    { name: "country", label: "Country", type: "select", options: COUNTRY_OPTIONS },
    { name: "photo_url", label: "Profile photo", type: "image", mediaCategory: "General" },
    { name: "quote", label: "Testimonial", type: "textarea", required: true },
    { name: "rating", label: "Rating (optional)", type: "number", placeholder: "5" },
    { name: "program_id", label: "Program", type: "relation", relation: { table: "programs", labelColumn: "name" } },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "featured", label: "Featured", type: "switch" },
    { name: "published", label: "Published (approved)", type: "switch" },
  ],
};

export const workshopsResource: ResourceConfig = {
  table: "workshops",
  title: "Workshops & Events",
  singular: "Workshop",
  description: "Upcoming and past workshops shown on the public Workshops page.",
  listPrimary: "name",
  listSecondary: ["event_date", "city", "country"],
  imageColumn: "image_url",
  searchColumns: ["name", "location", "city", "country", "description"],
  filters: [
    { column: "status", label: "Statuses", options: ["Upcoming", "Completed", "Cancelled", "Draft"] },
    { column: "country", label: "Countries", options: COUNTRY_OPTIONS },
  ],
  orderColumn: "display_order",
  publishColumn: "published",
  statusColumn: "status",
  softDelete: true,
  previewPath: "/workshops",
  emptyTitle: "No workshops added yet.",
  emptyBody: "Add an upcoming or past workshop.",
  defaultValues: { status: "Upcoming" },
  fields: [
    { name: "name", label: "Workshop name", type: "text", required: true },
    { name: "program_id", label: "Program", type: "relation", relation: { table: "programs", labelColumn: "name" } },
    { name: "event_date", label: "Date", type: "date" },
    { name: "start_time", label: "Start time", type: "time" },
    { name: "end_time", label: "End time", type: "time" },
    { name: "location", label: "Location", type: "text" },
    { name: "country", label: "Country", type: "select", options: COUNTRY_OPTIONS },
    { name: "city", label: "City", type: "text" },
    { name: "institution_id", label: "Institution", type: "relation", relation: { table: "institutions", labelColumn: "name" } },
    { name: "trainer_id", label: "Trainer", type: "relation", relation: { table: "trainers", labelColumn: "name" } },
    { name: "description", label: "Description", type: "richtext" },
    { name: "image_url", label: "Event image", type: "image", mediaCategory: "Events" },
    { name: "gallery_images", label: "Gallery", type: "gallery", mediaCategory: "Events" },
    { name: "registration_link", label: "Registration link", type: "text" },
    { name: "status", label: "Status", type: "select", options: ["Upcoming", "Completed", "Cancelled", "Draft"] },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const impactStatsResource: ResourceConfig = {
  table: "impact_stats",
  title: "Impact Statistics",
  singular: "Statistic",
  description: "The numbers shown on the homepage and Our Impact page. Nothing here changes automatically.",
  listPrimary: "value",
  listSecondary: ["label", "description"],
  searchColumns: ["value", "label", "description"],
  orderColumn: "display_order",
  publishColumn: "published",
  softDelete: true,
  previewPath: "/impact",
  emptyTitle: "No statistics yet.",
  emptyBody: "Add a statistic, for example 26 Lakh+ School Students.",
  fields: [
    { name: "value", label: "Number", type: "text", required: true, placeholder: "26 Lakh+" },
    { name: "label", label: "Label", type: "text", required: true, placeholder: "School Students" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "icon", label: "Icon name", type: "text", placeholder: "users", help: "Optional Lucide icon name." },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const enquiriesResource: ResourceConfig = {
  table: "enquiries",
  title: "Enquiries",
  singular: "Enquiry",
  description: "Every website enquiry lands here. This information is never shown publicly.",
  listPrimary: "name",
  listSecondary: ["organization", "email", "country"],
  searchColumns: ["name", "organization", "email", "phone", "country", "training_requirement", "message"],
  filters: [
    { column: "status", label: "Statuses", options: ["New", "Contacted", "Follow-up", "Converted", "Closed"] },
    { column: "country", label: "Countries", options: COUNTRY_OPTIONS },
  ],
  statusColumn: "status",
  softDelete: true,
  canCreate: false,
  emptyTitle: "No enquiries yet.",
  emptyBody: "Enquiries submitted through the website contact form will appear here.",
  fields: [
    { name: "name", label: "Name", type: "readonly" },
    { name: "organization", label: "Organization", type: "readonly" },
    { name: "designation", label: "Designation", type: "readonly" },
    { name: "email", label: "Email", type: "readonly" },
    { name: "phone", label: "Phone", type: "readonly" },
    { name: "whatsapp", label: "WhatsApp", type: "readonly" },
    { name: "country", label: "Country", type: "readonly" },
    { name: "training_requirement", label: "Training requirement", type: "readonly" },
    { name: "preferred_date", label: "Preferred date", type: "readonly" },
    { name: "participants", label: "Number of participants", type: "readonly" },
    { name: "message", label: "Message", type: "readonly", full: true },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: ["New", "Contacted", "Follow-up", "Converted", "Closed"],
    },
    { name: "internal_notes", label: "Internal notes", type: "textarea" },
  ],
};

export const navigationResource: ResourceConfig = {
  table: "navigation",
  title: "Navigation",
  singular: "Menu item",
  description: "Header and footer menus. Use a parent item to create a dropdown.",
  listPrimary: "label",
  listSecondary: ["url", "location"],
  searchColumns: ["label", "url"],
  filters: [{ column: "location", label: "Locations", options: ["header", "footer"] }],
  orderColumn: "display_order",
  publishColumn: "visible",
  emptyTitle: "No menu items yet.",
  emptyBody: "Add your first menu item.",
  defaultValues: { location: "header", visible: true, url: "/" },
  fields: [
    { name: "label", label: "Label", type: "text", required: true },
    { name: "url", label: "URL", type: "text", required: true, placeholder: "/programs" },
    { name: "location", label: "Location", type: "select", options: ["header", "footer"] },
    { name: "parent_id", label: "Parent item (for dropdowns)", type: "relation", relation: { table: "navigation", labelColumn: "label" } },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "visible", label: "Visible", type: "switch" },
  ],
};

export const seoResource: ResourceConfig = {
  table: "seo_settings",
  title: "SEO Settings",
  singular: "Page",
  description: "Search and social preview settings for each major page.",
  listPrimary: "page_label",
  listSecondary: ["seo_title", "focus_keyword"],
  searchColumns: ["page_label", "page_key", "seo_title", "focus_keyword"],
  emptyTitle: "No SEO pages configured.",
  emptyBody: "Add a page to manage its SEO settings.",
  fields: [
    { name: "page_label", label: "Page name", type: "text", required: true },
    { name: "page_key", label: "Page key", type: "text", required: true, placeholder: "programs" },
    { name: "seo_title", label: "SEO title", type: "text", help: "Aim for under 60 characters." },
    { name: "meta_description", label: "Meta description", type: "textarea", help: "Aim for under 160 characters." },
    { name: "focus_keyword", label: "Focus keyword", type: "text" },
    { name: "og_image_url", label: "Open Graph image", type: "image", mediaCategory: "General" },
    { name: "canonical_url", label: "Canonical URL", type: "text" },
    { name: "robots_index", label: "Allow search engines to index", type: "switch" },
  ],
};

export const CREDENTIAL_CATEGORIES = [
  "International",
  "Education",
  "Training",
  "Professional",
  "Other",
];

export const credentialsResource: ResourceConfig = {
  table: "credentials",
  title: "Credentials & Certificates",
  singular: "Credential",
  description: "Certificates and appreciation letters shown on the homepage and the Credentials page.",
  listPrimary: "title",
  listSecondary: ["issuing_organization", "category", "year"],
  imageColumn: "image_url",
  searchColumns: ["title", "issuing_organization", "category", "description"],
  filters: [{ column: "category", label: "Categories", options: CREDENTIAL_CATEGORIES }],
  orderColumn: "display_order",
  publishColumn: "published",
  featuredColumn: "featured",
  softDelete: true,
  previewPath: "/credentials",
  emptyTitle: "No credentials yet.",
  emptyBody: "Upload a certificate or appreciation letter to build the credentials wall.",
  fields: [
    { name: "image_url", label: "Certificate image", type: "image", required: true, mediaCategory: "General" },
    { name: "title", label: "Certificate title", type: "text", required: true },
    { name: "issuing_organization", label: "Issuing organisation", type: "text" },
    { name: "certificate_date", label: "Date", type: "date" },
    { name: "year", label: "Year", type: "number" },
    { name: "category", label: "Category", type: "select", options: CREDENTIAL_CATEGORIES },
    { name: "description", label: "Description", type: "textarea" },
    { name: "alt_text", label: "Alt text", type: "text", help: "Describes the certificate for accessibility and SEO." },
    { name: "display_order", label: "Display order", type: "number" },
    { name: "featured", label: "Featured", type: "switch" },
    { name: "show_on_homepage", label: "Show on homepage", type: "switch" },
    { name: "show_on_credentials_page", label: "Show on credentials page", type: "switch" },
    { name: "published", label: "Published", type: "switch" },
  ],
};
