/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GlobalReachRouteImport } from './routes/global-reach'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCountriesRouteImport } from './routes/admin.countries'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminInstitutionsRouteImport } from './routes/admin.institutions'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminTopicsRouteImport } from './routes/admin.topics'
import { Route as AdminTrainersRouteImport } from './routes/admin.trainers'
import { Route as AdminWorkshopsRouteImport } from './routes/admin.workshops'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalReachRoute = GlobalReachRouteImport.update({
  id: '/global-reach',
  path: '/global-reach',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCountriesRoute = AdminCountriesRouteImport.update({
  id: '/admin/countries',
  path: '/admin/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstitutionsRoute = AdminInstitutionsRouteImport.update({
  id: '/admin/institutions',
  path: '/admin/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/admin/navigation',
  path: '/admin/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/admin/programs',
  path: '/admin/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTopicsRoute = AdminTopicsRouteImport.update({
  id: '/admin/topics',
  path: '/admin/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainersRoute = AdminTrainersRouteImport.update({
  id: '/admin/trainers',
  path: '/admin/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkshopsRoute = AdminWorkshopsRouteImport.update({
  id: '/admin/workshops',
  path: '/admin/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/global-reach': typeof GlobalReachRoute
  '/institutions': typeof InstitutionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trainers': typeof TrainersRoute
  '/workshops': typeof WorkshopsRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/admin/workshops': typeof AdminWorkshopsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/global-reach': typeof GlobalReachRoute
  '/institutions': typeof InstitutionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trainers': typeof TrainersRoute
  '/workshops': typeof WorkshopsRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/admin/workshops': typeof AdminWorkshopsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/global-reach': typeof GlobalReachRoute
  '/institutions': typeof InstitutionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trainers': typeof TrainersRoute
  '/workshops': typeof WorkshopsRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/admin/workshops': typeof AdminWorkshopsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/global-reach'
    | '/institutions'
    | '/reset-password'
    | '/trainers'
    | '/workshops'
    | '/admin/countries'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/institutions'
    | '/admin/navigation'
    | '/admin/programs'
    | '/admin/seo'
    | '/admin/testimonials'
    | '/admin/topics'
    | '/admin/trainers'
    | '/admin/workshops'
    | '/programs/$slug'
    | '/admin/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/global-reach'
    | '/institutions'
    | '/reset-password'
    | '/trainers'
    | '/workshops'
    | '/admin/countries'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/institutions'
    | '/admin/navigation'
    | '/admin/programs'
    | '/admin/seo'
    | '/admin/testimonials'
    | '/admin/topics'
    | '/admin/trainers'
    | '/admin/workshops'
    | '/programs/$slug'
    | '/admin'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/global-reach'
    | '/institutions'
    | '/reset-password'
    | '/trainers'
    | '/workshops'
    | '/admin/countries'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/institutions'
    | '/admin/navigation'
    | '/admin/programs'
    | '/admin/seo'
    | '/admin/testimonials'
    | '/admin/topics'
    | '/admin/trainers'
    | '/admin/workshops'
    | '/programs/$slug'
    | '/admin/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GlobalReachRoute: typeof GlobalReachRoute
  InstitutionsRoute: typeof InstitutionsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrainersRoute: typeof TrainersRoute
  WorkshopsRoute: typeof WorkshopsRoute
  AdminCountriesRoute: typeof AdminCountriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminInstitutionsRoute: typeof AdminInstitutionsRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTopicsRoute: typeof AdminTopicsRoute
  AdminTrainersRoute: typeof AdminTrainersRoute
  AdminWorkshopsRoute: typeof AdminWorkshopsRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-reach': {
      id: '/global-reach'
      path: '/global-reach'
      fullPath: '/global-reach'
      preLoaderRoute: typeof GlobalReachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/countries': {
      id: '/admin/countries'
      path: '/admin/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AdminCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institutions': {
      id: '/admin/institutions'
      path: '/admin/institutions'
      fullPath: '/admin/institutions'
      preLoaderRoute: typeof AdminInstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/admin/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/admin/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/topics': {
      id: '/admin/topics'
      path: '/admin/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AdminTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainers': {
      id: '/admin/trainers'
      path: '/admin/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AdminTrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workshops': {
      id: '/admin/workshops'
      path: '/admin/workshops'
      fullPath: '/admin/workshops'
      preLoaderRoute: typeof AdminWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GlobalReachRoute: GlobalReachRoute,
  InstitutionsRoute: InstitutionsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrainersRoute: TrainersRoute,
  WorkshopsRoute: WorkshopsRoute,
  AdminCountriesRoute: AdminCountriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminInstitutionsRoute: AdminInstitutionsRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTopicsRoute: AdminTopicsRoute,
  AdminTrainersRoute: AdminTrainersRoute,
  AdminWorkshopsRoute: AdminWorkshopsRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
